FROM registry.redhat.io/ubi8/ubi:8.4

USER root
RUN dnf -y install nodejs git &&\
  npm install -g meteor

RUN chown -R 1001:0 /meteor && chmod -R ug+rwx /meteor && \
  rpm-file-permissions

USER 1001
WORKDIR /meteor

RUN npm install -g meteor
