FROM registry.redhat.io/ubi7/ubi:7.9

USER root
RUN dnf -y install curl &&\
  curl -sL https://rpm.nodesource.com/setup_14.x -o setup_nodejs_14.sh &&\
  /bin/bash setup_nodejs_14.sh &&\
  dnf -y install nodejs

RUN chown -R 1001:0 /meteor && chmod -R ug+rwx /meteor && \
  rpm-file-permissions

USER 1001
WORKDIR /meteor

RUN npm install -g meteor
