FROM registry.redhat.io/ubi8/ubi:8.4

USER root
RUN dnf -y install nodejs git
#RUN npm install -g meteor
RUN git clone https://github.com/meteor/meteor /meteor

RUN chown -R 1001:0 "/.npm" &&\
  chown -R 1001:0 /meteor &&\
  chmod -R ug+rwx /meteor

USER 1001
WORKDIR /meteor

RUN npm install -g meteor
